### ISSUE TITLE
Documentation links in README.md are broken

### ISSUE THREAD

**Issue by dimsuz** [alpmestan/taggy-lens#2]
Links to documentation on your server are broken.
Talking about these ones:

> I try to keep an up-to-date copy of the docs on my server:
> 
> - [taggy](http://alpmestan.com/taggy/)
> - [taggy-lens](http://alpmestan.com/taggy-lens/)

Both give a 404 error. Perhaps you should either update docs or README...

**Comment by fmap** [comment]
https://hackage.haskell.org/package/taggy
https://hackage.haskell.org/package/taggy-lens

Patch incoming.

**Comment by alpmestan** [comment]
Yeah, I have moved my server since then sorry for the inconvenience!
