### ISSUE TITLE
is there a way to save parsing effort when you want to apply a set of lens operations to an html doc?

### ISSUE THREAD

**Issue by mwotton** [alpmestan/taggy-lens#6]
Apologies, this is probably just because I don't understand the system very well, but I'm having real trouble working out how to apply a list of lenses to a single html document.

using the example in the docs:

```
 recentPackages :: Response ByteString -> [Maybe Upload]
 recentPackages = toListOf
                $ responseBody . to (decodeUtf8With lenientDecode)
                . html . rows

rows = allNamed (only "tr") . children . to table
```

say instead of just rows, I had a dozen different lenses to apply. obviously if i just abstract the lens to apply out and call each of them in order, I'll get the right answer, but it ends up dreadfully slow as the parsing happens again for each lens.

**Comment by alpmestan** [comment]
Something like:

``` haskell
 recentPackages :: Response ByteString -> [Maybe Upload]
 recentPackages = toListOf
                $ responseBody . to (decodeUtf8With lenientDecode)
                . html . to allTheDataIWant

allTheDataIWant :: Node -> Maybe (A, B, C, D, E, F)
allTheDataIWant root = do
  a <- root ^.. allNamed (only "tr" . ...
  b <- root ^.. allNamed (only "<b>") . ...
  -- etc
```

?

**Comment by mwotton** [comment]
thanks so much :)
